import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { ThemeProvider } from '@mui/material'
import theme from '@/common/theme/theme'
import { SnackbarProvider } from '@/context/snackbarContext'
import { UserProvider } from '@/context/userContext'
import { ApiProvider } from '@/context/apiContext'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <SnackbarProvider>
        <ApiProvider>
          <UserProvider>
            <ThemeProvider theme={theme}>
              <body className={inter.className}>{children}</body>
            </ThemeProvider>
          </UserProvider>
        </ApiProvider>
      </SnackbarProvider>
    </html>
  )
}
